export const translations = {
  en: {
    mainMenu: {
      title: 'Strategix',
      play: 'Play Chess',
      load: 'Load Game',
      stats: 'Statistics',
      settings: 'Settings',
      help: 'Help / Tutorial',
      exit: 'Exit',
    },
    playMenu: {
        title: 'Play Chess',
        vsAI: 'vs. AI',
        local: 'vs. Human',
        tutorial: 'Training / Tutorial',
        difficulty: 'Difficulty',
        easy: 'Easy',
        medium: 'Medium',
        hard: 'Hard',
        master: 'Master',
        easyDesc: 'A casual game, good for learning.',
        mediumDesc: 'A balanced challenge for most players.',
        hardDesc: 'A tough opponent that punishes mistakes.',
        masterDesc: 'Maximum challenge. Plays near-optimal moves.',
        pieceColor: 'Piece Color',
        white: 'White',
        black: 'Black',
        random: 'Random',
        moveHints: 'Move Hints',
        start: 'Start Game',
        onlineComingSoon: 'Online Mode - Coming Soon',
    },
    loadMenu: {
        title: 'Load Game',
        empty: 'No saved games found.',
        load: 'Load',
        delete: 'Delete',
    },
    statsMenu: {
        title: 'Statistics',
        totalGames: 'Total Games',
        wins: 'Wins',
        losses: 'Losses',
        draws: 'Draws',
        rating: 'Offline Rating',
        winLossRatio: 'Win/Loss Ratio',
        mostUsedOpenings: 'Most Used Openings',
    },
    settingsMenu: {
        title: 'Settings',
        language: 'Language',
        sound: 'Sound',
        music: 'Music',
        on: 'On',
        off: 'Off',
        theme: 'Board Theme',
        light: 'Light',
        dark: 'Dark',
        animationSpeed: 'Animation Speed',
        fast: 'Fast',
        normal: 'Normal',
        slow: 'Slow',
        resetStats: 'Reset Statistics',
        resetConfirm: 'Are you sure you want to reset all stats? This cannot be undone.',
        confirm: 'Confirm',
    },
    helpMenu: {
        title: 'Help / Tutorial',
        rules: 'Basic Rules (FIDE)',
        pawn: 'Pawn: Moves one square forward, but two on its first move. Captures diagonally.',
        knight: 'Knight: Moves in an "L" shape (two squares in one direction, then one perpendicularly).',
        bishop: 'Bishop: Moves diagonally any number of squares.',
        rook: 'Rook: Moves horizontally or vertically any number of squares.',
        queen: 'Queen: Combines the power of the rook and bishop.',
        king: 'King: Moves one square in any direction.',
        faq: 'FAQ',
        faq1_q: 'Is this app 100% offline?',
        faq1_a: 'Yes, all features are designed to work without an internet connection.',
        viewTerms: 'View Terms & Conditions',
    },
    termsModal: {
      title: 'Terms & Conditions',
      content: `STRATEGIX TERMS AND CONDITIONS AND PRIVACY POLICY

Last updated: September 21, 2025

1. Introduction
Welcome to Strategix, a 100% offline chess web application. By accessing or using Strategix, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree with any of these terms, do not use the application.

2. Ownership and Credits
Strategix is owned by Benzanox Studios. Although the Gemini 2.5 Pro AI was used for development, all intellectual property rights of the app belong to you as the app owner.

3. Use of the Application
3.1 Strategix is an application intended for entertainment and chess learning purposes.
3.2 You agree not to use the application for illegal activities, including piracy, hacking, or violating the rights of third parties.
3.3 The application runs completely offline and does not collect any external data.

4. User Content and Storage
4.1 All data generated by you, including games and settings, is kept exclusively in your device's LocalStorage.
4.2 Strategix does not collect, transmit, or share personal or game data with external servers.
4.3 You are responsible for maintaining the security of your device and the data stored locally.

5. License to Use
5.1 You are granted a limited, non-exclusive, non-transferable license to use Strategix in your browser.
5.2 You are not permitted to redistribute, sell, decompile, or create derivative works from the application without express authorization.

6. Intellectual Property
6.1 All copyrights, trademarks, and graphic designs of Strategix, including the chess pieces and interface, are the property of Benzanox Studios.
6.2 The user does not acquire any intellectual property rights by using the application.

7. Limitation of Liability
7.1 Strategix is provided "as is" and does not guarantee that the application will be free of errors or interruptions.
7.2 Benzanox Studios will not be liable for any direct, indirect, incidental, or consequential damages arising from the use of the application.

8. Modifications and Updates
8.1 Benzanox Studios may update or modify Strategix and these terms at any time.
8.2 It is recommended to review this section periodically. Continued use implies acceptance of the changes.

9. User Responsibility
9.1 The user is responsible for the proper use of the application and for the secure maintenance of their local data.
9.2 It is recommended to make backups of important games and settings to avoid information loss due to device failures.
9.3 Any misuse that causes damage to third parties is the exclusive responsibility of the user.

10. Privacy Policy
10.1 No personal data is collected from users.
10.2 All information about games, statistics, and settings is stored only in your browser's LocalStorage.
10.3 No information is shared with third parties under any circumstances.
10.4 The application does not perform tracking or use external cookies; any cookies used are strictly for internal operation.

11. Applicable Law and Jurisdiction
11.1 These terms are governed by the Law of the Republic of Paraguay.
11.2 Any legal dispute related to the application will be resolved exclusively in the courts of Asunción, Paraguay.

12. Contact
For questions about these terms, you can contact us at: [dinerocor@hotmail.com]

By using Strategix, you accept these Terms and Conditions and our Privacy Policy in their entirety, with the assurance that no personal data is collected or transmitted outside of your device.`,
      agree: 'I have read and agree to the terms and conditions.',
      accept: 'Accept',
    },
    common: {
        back: 'Back',
        cancel: 'Cancel',
        comingSoon: 'Coming Soon',
    }
  },
  es: {
    mainMenu: {
      title: 'Strategix',
      play: 'Jugar Ajedrez',
      load: 'Cargar Partida',
      stats: 'Estadísticas',
      settings: 'Configuración',
      help: 'Ayuda / Tutorial',
      exit: 'Salir',
    },
    playMenu: {
        title: 'Jugar Ajedrez',
        vsAI: 'vs. IA',
        local: 'vs. Humano',
        tutorial: 'Entrenamiento / Tutorial',
        difficulty: 'Dificultad',
        easy: 'Fácil',
        medium: 'Medio',
        hard: 'Difícil',
        master: 'Maestro',
        easyDesc: 'Una partida casual, buena para aprender.',
        mediumDesc: 'Un desafío equilibrado para la mayoría de jugadores.',
        hardDesc: 'Un oponente duro que castiga los errores.',
        masterDesc: 'Desafío máximo. Juega movimientos casi óptimos.',
        pieceColor: 'Color de Piezas',
        white: 'Blancas',
        black: 'Negras',
        random: 'Aleatorio',
        moveHints: 'Sugerencias',
        start: 'Iniciar Partida',
        onlineComingSoon: 'Modo Online - Próximamente',
    },
    loadMenu: {
        title: 'Cargar Partida',
        empty: 'No se encontraron partidas guardadas.',
        load: 'Cargar',
        delete: 'Borrar',
    },
    statsMenu: {
        title: 'Estadísticas',
        totalGames: 'Partidas Totales',
        wins: 'Victorias',
        losses: 'Derrotas',
        draws: 'Tablas',
        rating: 'Rating Offline',
        winLossRatio: 'Ratio Victoria/Derrota',
        mostUsedOpenings: 'Aperturas Más Usadas',
    },
    settingsMenu: {
        title: 'Configuración',
        language: 'Idioma',
        sound: 'Sonido',
        music: 'Música',
        on: 'Activado',
        off: 'Desactivado',
        theme: 'Tema del Tablero',
        light: 'Claro',
        dark: 'Oscuro',
        animationSpeed: 'Velocidad de Animación',
        fast: 'Rápida',
        normal: 'Normal',
        slow: 'Lenta',
        resetStats: 'Reiniciar Estadísticas',
        resetConfirm: '¿Estás seguro de que quieres reiniciar todas las estadísticas? Esta acción no se puede deshacer.',
        confirm: 'Confirmar',
    },
    helpMenu: {
        title: 'Ayuda / Tutorial',
        rules: 'Reglas Básicas (FIDE)',
        pawn: 'Peón: Mueve una casilla hacia adelante, pero dos en su primer movimiento. Captura en diagonal.',
        knight: 'Caballo: Mueve en forma de "L" (dos casillas en una dirección, luego una perpendicularmente).',
        bishop: 'Alfil: Mueve en diagonal cualquier número de casillas.',
        rook: 'Torre: Mueve horizontal o verticalmente cualquier número de casillas.',
        queen: 'Dama: Combina el poder de la torre y el alfil.',
        king: 'Rey: Mueve una casilla en cualquier dirección.',
        faq: 'Preguntas Frecuentes',
        faq1_q: '¿Esta app es 100% offline?',
        faq1_a: 'Sí, todas las funciones están diseñadas para funcionar sin conexión a internet.',
        viewTerms: 'Ver Términos y Condiciones',
    },
    termsModal: {
      title: 'Términos y Condiciones',
      content: `TÉRMINOS Y CONDICIONES Y POLÍTICA DE PRIVACIDAD DE STRATEGIX

Última actualización: 21 de septiembre de 2025

1. Introducción
Bienvenido a Strategix, una aplicación web de ajedrez 100% offline. Al acceder o utilizar Strategix, usted acepta estar sujeto a estos Términos y Condiciones y a nuestra Política de Privacidad. Si no está de acuerdo con alguno de estos términos, no use la aplicación.

2. Propiedad y créditos
Strategix es propiedad de Benzanox Studios. Aunque la IA Gemini 2.5 Pro se utilizó para el desarrollo, todos los derechos de propiedad intelectual de la app pertenecen a usted como titular de la app.

3. Uso de la aplicación
3.1 Strategix es una aplicación destinada a fines de entretenimiento y aprendizaje del ajedrez.
3.2 Usted acepta no utilizar la aplicación para actividades ilegales, incluyendo piratería, hacking o violación de derechos de terceros.
3.3 La aplicación se ejecuta completamente offline y no recopila datos externos de ningún tipo.

4. Contenido del usuario y almacenamiento
4.1 Todos los datos generados por usted, incluyendo partidas y configuraciones, se mantienen exclusivamente en LocalStorage de su dispositivo.
4.2 Strategix no recopila, transmite ni comparte datos personales o de juego con servidores externos.
4.3 Usted es responsable de mantener la seguridad de su dispositivo y de los datos almacenados localmente.

5. Licencia de uso
5.1 Se le concede una licencia limitada, no exclusiva e intransferible para usar Strategix en su navegador.
5.2 No se permite redistribuir, vender, descompilar o crear trabajos derivados de la aplicación sin autorización expresa.

6. Propiedad intelectual
6.1 Todos los derechos de autor, marcas y diseños gráficos de Strategix, incluidas las piezas de ajedrez y la interfaz, son propiedad de Benzanox Studios.
6.2 El usuario no adquiere derechos de propiedad intelectual al usar la aplicación.

7. Limitación de responsabilidad
7.1 Strategix se proporciona "tal cual" y no garantiza que la aplicación esté libre de errores o interrupciones.
7.2 Benzanox Studios no será responsable de ningún daño directo, indirecto, incidental o consecuente derivado del uso de la aplicación.

8. Modificaciones y actualizaciones
8.1 Benzanox Studios puede actualizar o modificar Strategix y estos términos en cualquier momento.
8.2 Se recomienda revisar periódicamente esta sección. El uso continuado implica aceptación de los cambios.

9. Responsabilidad del usuario
9.1 El usuario es responsable del uso adecuado de la aplicación y del mantenimiento seguro de sus datos locales.
9.2 Se recomienda realizar respaldos de las partidas y configuraciones importantes para evitar pérdida de información debido a fallos del dispositivo.
9.3 Cualquier uso indebido que genere daños a terceros es responsabilidad exclusiva del usuario.

10. Política de privacidad
10.1 No se recopilan datos personales de los usuarios.
10.2 Toda la información sobre partidas, estadísticas y configuraciones se almacena únicamente en LocalStorage de su navegador.
10.3 No se comparte información con terceros bajo ninguna circunstancia.
10.4 La aplicación no realiza rastreo ni uso de cookies externas; cualquier cookie usada es estrictamente para funcionamiento interno.

11. Ley aplicable y jurisdicción
11.1 Estos términos se rigen por la Ley de la República del Paraguay.
11.2 Cualquier disputa legal relacionada con la aplicación se resolverá exclusivamente en los tribunales de Asunción, Paraguay.

12. Contacto
Para preguntas sobre estos términos, puede contactarnos en: [dinerocor@hotmail.com]

Al usar Strategix, usted acepta estos Términos y Condiciones y nuestra Política de Privacidad en su totalidad, con la seguridad de que ningún dato personal se recopila ni se transmite fuera de su dispositivo.`,
      agree: 'He leído y acepto los términos y condiciones.',
      accept: 'Aceptar',
    },
    common: {
        back: 'Volver',
        cancel: 'Cancelar',
        comingSoon: 'Próximamente',
    }
  },
  fr: {
    mainMenu: {
      title: 'Strategix',
      play: 'Jouer aux échecs',
      load: 'Charger une partie',
      stats: 'Statistiques',
      settings: 'Paramètres',
      help: 'Aide / Tutoriel',
      exit: 'Quitter',
    },
    playMenu: {
        title: 'Jouer aux échecs',
        vsAI: 'vs. IA',
        local: 'vs. Humain',
        tutorial: 'Entraînement / Tutoriel',
        difficulty: 'Difficulté',
        easy: 'Facile',
        medium: 'Moyen',
        hard: 'Difficile',
        master: 'Maître',
        easyDesc: 'Une partie décontractée, bonne pour apprendre.',
        mediumDesc: 'Un défi équilibré pour la plupart des joueurs.',
        hardDesc: 'Un adversaire redoutable qui punit les erreurs.',
        masterDesc: 'Défi maximum. Joue des coups quasi optimaux.',
        pieceColor: 'Couleur des pièces',
        white: 'Blancs',
        black: 'Noirs',
        random: 'Aléatoire',
        moveHints: 'Indices de coups',
        start: 'Commencer la partie',
        onlineComingSoon: 'Mode en ligne - Bientôt disponible',
    },
    loadMenu: {
        title: 'Charger une partie',
        empty: 'Aucune partie sauvegardée trouvée.',
        load: 'Charger',
        delete: 'Supprimer',
    },
    statsMenu: {
        title: 'Statistiques',
        totalGames: 'Parties totales',
        wins: 'Victoires',
        losses: 'Défaites',
        draws: 'Matchs nuls',
        rating: 'Classement hors ligne',
        winLossRatio: 'Ratio Victoires/Défaites',
        mostUsedOpenings: 'Ouvertures les plus utilisées',
    },
    settingsMenu: {
        title: 'Paramètres',
        language: 'Langue',
        sound: 'Son',
        music: 'Musique',
        on: 'Activé',
        off: 'Désactivé',
        theme: 'Thème de l\'échiquier',
        light: 'Clair',
        dark: 'Sombre',
        animationSpeed: 'Vitesse d\'animation',
        fast: 'Rapide',
        normal: 'Normale',
        slow: 'Lente',
        resetStats: 'Réinitialiser les statistiques',
        resetConfirm: 'Êtes-vous sûr de vouloir réinitialiser toutes les statistiques ? Cette action est irréversible.',
        confirm: 'Confirmer',
    },
    helpMenu: {
        title: 'Aide / Tutoriel',
        rules: 'Règles de base (FIDE)',
        pawn: 'Pion : Avance d\'une case, ou de deux à son premier coup. Capture en diagonale.',
        knight: 'Cavalier : Se déplace en "L" (deux cases dans une direction, puis une perpendiculairement).',
        bishop: 'Fou : Se déplace en diagonale sur n\'importe quel nombre de cases.',
        rook: 'Tour : Se déplace horizontalement ou verticalement sur n\'importe quel nombre de cases.',
        queen: 'Dame : Combine la puissance de la tour et du fou.',
        king: 'Roi : Se déplace d\'une case dans n\'importe quelle direction.',
        faq: 'FAQ',
        faq1_q: 'Cette application est-elle 100% hors ligne ?',
        faq1_a: 'Oui, toutes les fonctionnalités sont conçues pour fonctionner sans connexion Internet.',
        viewTerms: 'Consulter les Termes et Conditions',
    },
    termsModal: {
      title: 'Termes et Conditions',
      content: `TERMES ET CONDITIONS ET POLITIQUE DE CONFIDENTIALITÉ DE STRATEGIX

Dernière mise à jour : 21 septembre 2025

1. Introduction
Bienvenue sur Strategix, une application web d'échecs 100% hors ligne. En accédant ou en utilisant Strategix, vous acceptez d'être lié par ces Termes et Conditions et notre Politique de Confidentialité. Si vous n'êtes pas d'accord avec l'un de ces termes, n'utilisez pas l'application.

2. Propriété et crédits
Strategix est la propriété de Benzanox Studios. Bien que l'IA Gemini 2.5 Pro ait été utilisée pour le développement, tous les droits de propriété intellectuelle de l'application vous appartiennent en tant que propriétaire de l'application.

3. Utilisation de l'application
3.1 Strategix est une application destinée au divertissement et à l'apprentissage des échecs.
3.2 Vous acceptez de ne pas utiliser l'application pour des activités illégales, y compris le piratage, le hacking ou la violation des droits de tiers.
3.3 L'application fonctionne entièrement hors ligne et ne collecte aucune donnée externe.

4. Contenu utilisateur et stockage
4.1 Toutes les données que vous générez, y compris les parties et les paramètres, sont conservées exclusivement dans le LocalStorage de votre appareil.
4.2 Strategix ne collecte, ne transmet ni ne partage de données personnelles ou de jeu avec des serveurs externes.
4.3 Vous êtes responsable du maintien de la sécurité de votre appareil et des données stockées localement.

5. Licence d'utilisation
5.1 Il vous est accordé une licence limitée, non exclusive et non transférable pour utiliser Strategix dans votre navigateur.
5.2 Il est interdit de redistribuer, vendre, décompiler ou créer des œuvres dérivées de l'application sans autorisation expresse.

6. Propriété intellectuelle
6.1 Tous les droits d'auteur, marques et conceptions graphiques de Strategix, y compris les pièces d'échecs et l'interface, sont la propriété de Benzanox Studios.
6.2 L'utilisateur n'acquiert aucun droit de propriété intellectuelle en utilisant l'application.

7. Limitation de responsabilité
7.1 Strategix est fourni « tel quel » et ne garantit pas que l'application sera exempte d'erreurs ou d'interruptions.
7.2 Benzanox Studios ne sera pas responsable des dommages directs, indirects, accessoires ou consécutifs découlant de l'utilisation de l'application.

8. Modifications et mises à jour
8.1 Benzanox Studios peut mettre à jour ou modifier Strategix et ces termes à tout moment.
8.2 Il est recommandé de consulter cette section périodiquement. L'utilisation continue implique l'acceptation des modifications.

9. Responsabilité de l'utilisateur
9.1 L'utilisateur est responsable de l'utilisation appropriée de l'application et de la maintenance sécurisée de ses données locales.
9.2 Il est recommandé de faire des sauvegardes des parties et des paramètres importants pour éviter la perte d'informations due à des pannes de l'appareil.
9.3 Toute utilisation abusive causant des dommages à des tiers relève de la responsabilité exclusive de l'utilisateur.

10. Politique de confidentialité
10.1 Aucune donnée personnelle n'est collectée auprès des utilisateurs.
10.2 Toutes les informations sur les parties, les statistiques et les paramètres sont stockées uniquement dans le LocalStorage de votre navigateur.
10.3 Aucune information n'est partagée avec des tiers en aucune circonstance.
10.4 L'application n'effectue aucun suivi et n'utilise pas de cookies externes ; tout cookie utilisé est strictement destiné au fonctionnement interne.

11. Droit applicable et juridiction
11.1 Ces termes sont régis par la loi de la République du Paraguay.
11.2 Tout litige juridique lié à l'application sera résolu exclusivement devant les tribunaux d'Asunción, Paraguay.

12. Contact
Pour toute question sur ces termes, vous pouvez nous contacter à : [dinerocor@hotmail.com]

En utilisant Strategix, vous acceptez ces Termes et Conditions et notre Politique de Confidentialité dans leur intégralité, avec l'assurance qu'aucune donnée personnelle n'est collectée ou transmise en dehors de votre appareil.`,
      agree: 'J\'ai lu et j\'accepte les termes et conditions.',
      accept: 'Accepter',
    },
    common: {
        back: 'Retour',
        cancel: 'Annuler',
        comingSoon: 'Bientôt disponible',
    }
  },
  de: {
    mainMenu: {
      title: 'Strategix',
      play: 'Schach spielen',
      load: 'Spiel laden',
      stats: 'Statistiken',
      settings: 'Einstellungen',
      help: 'Hilfe / Tutorial',
      exit: 'Beenden',
    },
    playMenu: {
        title: 'Schach spielen',
        vsAI: 'vs. KI',
        local: 'vs. Mensch',
        tutorial: 'Training / Tutorial',
        difficulty: 'Schwierigkeit',
        easy: 'Leicht',
        medium: 'Mittel',
        hard: 'Schwer',
        master: 'Meister',
        easyDesc: 'Ein lockeres Spiel, gut zum Lernen.',
        mediumDesc: 'Eine ausgewogene Herausforderung für die meisten Spieler.',
        hardDesc: 'Ein zäher Gegner, der Fehler bestraft.',
        masterDesc: 'Maximale Herausforderung. Spielt nahezu optimale Züge.',
        pieceColor: 'Figurenfarbe',
        white: 'Weiß',
        black: 'Schwarz',
        random: 'Zufällig',
        moveHints: 'Zughinweise',
        start: 'Spiel starten',
        onlineComingSoon: 'Online-Modus - Kommt bald',
    },
    loadMenu: {
        title: 'Spiel laden',
        empty: 'Keine gespeicherten Spiele gefunden.',
        load: 'Laden',
        delete: 'Löschen',
    },
    statsMenu: {
        title: 'Statistiken',
        totalGames: 'Gesamtspiele',
        wins: 'Siege',
        losses: 'Niederlagen',
        draws: 'Unentschieden',
        rating: 'Offline-Wertung',
        winLossRatio: 'Sieg/Niederlage-Verhältnis',
        mostUsedOpenings: 'Meistgenutzte Eröffnungen',
    },
    settingsMenu: {
        title: 'Einstellungen',
        language: 'Sprache',
        sound: 'Ton',
        music: 'Musik',
        on: 'An',
        off: 'Aus',
        theme: 'Brett-Thema',
        light: 'Hell',
        dark: 'Dunkel',
        animationSpeed: 'Animationsgeschwindigkeit',
        fast: 'Schnell',
        normal: 'Normal',
        slow: 'Langsam',
        resetStats: 'Statistiken zurücksetzen',
        resetConfirm: 'Sind Sie sicher, dass Sie alle Statistiken zurücksetzen möchten? Dies kann nicht rückgängig gemacht werden.',
        confirm: 'Bestätigen',
    },
    helpMenu: {
        title: 'Hilfe / Tutorial',
        rules: 'Grundregeln (FIDE)',
        pawn: 'Bauer: Zieht ein Feld vorwärts, aber zwei bei seinem ersten Zug. Schlägt diagonal.',
        knight: 'Springer: Bewegt sich in "L"-Form (zwei Felder in eine Richtung, dann eines senkrecht dazu).',
        bishop: 'Läufer: Zieht diagonal beliebig viele Felder.',
        rook: 'Turm: Zieht horizontal oder vertikal beliebig viele Felder.',
        queen: 'Dame: Kombiniert die Kraft von Turm und Läufer.',
        king: 'König: Zieht ein Feld in eine beliebige Richtung.',
        faq: 'FAQ',
        faq1_q: 'Ist diese App 100% offline?',
        faq1_a: 'Ja, alle Funktionen sind so konzipiert, dass sie ohne Internetverbindung funktionieren.',
        viewTerms: 'Nutzungsbedingungen anzeigen',
    },
    termsModal: {
      title: 'Allgemeine Geschäftsbedingungen',
      content: `ALLGEMEINE GESCHÄFTSBEDINGUNGEN UND DATENSCHUTZRICHTLINIE VON STRATEGIX

Letzte Aktualisierung: 21. September 2025

1. Einleitung
Willkommen bei Strategix, einer 100% Offline-Schach-Webanwendung. Durch den Zugriff auf oder die Nutzung von Strategix erklären Sie sich mit diesen Allgemeinen Geschäftsbedingungen und unserer Datenschutzrichtlinie einverstanden. Wenn Sie mit einer dieser Bedingungen nicht einverstanden sind, verwenden Sie die Anwendung nicht.

2. Eigentum und Danksagung
Strategix ist Eigentum von Benzanox Studios. Obwohl die Gemini 2.5 Pro KI für die Entwicklung verwendet wurde, gehören alle geistigen Eigentumsrechte der App Ihnen als App-Eigentümer.

3. Nutzung der Anwendung
3.1 Strategix ist eine Anwendung, die zu Unterhaltungs- und Schachlernzwecken bestimmt ist.
3.2 Sie stimmen zu, die Anwendung nicht für illegale Aktivitäten zu verwenden, einschließlich Piraterie, Hacking oder Verletzung der Rechte Dritter.
3.3 Die Anwendung läuft vollständig offline und sammelt keine externen Daten.

4. Benutzerinhalte und Speicherung
4.1 Alle von Ihnen generierten Daten, einschließlich Partien und Einstellungen, werden ausschließlich im LocalStorage Ihres Geräts gespeichert.
4.2 Strategix sammelt, überträgt oder teilt keine persönlichen oder Spieldaten mit externen Servern.
4.3 Sie sind für die Sicherheit Ihres Geräts und der lokal gespeicherten Daten verantwortlich.

5. Nutzungslizenz
5.1 Ihnen wird eine begrenzte, nicht-exklusive, nicht übertragbare Lizenz zur Nutzung von Strategix in Ihrem Browser gewährt.
5.2 Es ist nicht gestattet, die Anwendung ohne ausdrückliche Genehmigung weiterzuverbreiten, zu verkaufen, zu dekompilieren oder abgeleitete Werke davon zu erstellen.

6. Geistiges Eigentum
6.1 Alle Urheberrechte, Marken und Grafikdesigns von Strategix, einschließlich der Schachfiguren und der Benutzeroberfläche, sind Eigentum von Benzanox Studios.
6.2 Der Benutzer erwirbt durch die Nutzung der Anwendung keine geistigen Eigentumsrechte.

7. Haftungsbeschränkung
7.1 Strategix wird "wie besehen" zur Verfügung gestellt und garantiert nicht, dass die Anwendung fehler- oder unterbrechungsfrei ist.
7.2 Benzanox Studios haftet nicht für direkte, indirekte, zufällige oder Folgeschäden, die aus der Nutzung der Anwendung entstehen.

8. Änderungen und Aktualisierungen
8.1 Benzanox Studios kann Strategix und diese Bedingungen jederzeit aktualisieren oder ändern.
8.2 Es wird empfohlen, diesen Abschnitt regelmäßig zu überprüfen. Die fortgesetzte Nutzung gilt als Annahme der Änderungen.

9. Benutzerverantwortung
9.1 Der Benutzer ist für die ordnungsgemäße Nutzung der Anwendung und die sichere Pflege seiner lokalen Daten verantwortlich.
9.2 Es wird empfohlen, Sicherungskopien wichtiger Partien und Einstellungen zu erstellen, um Informationsverluste durch Geräteausfälle zu vermeiden.
9.3 Jeder Missbrauch, der Dritten Schaden zufügt, liegt in der alleinigen Verantwortung des Benutzers.

10. Datenschutzrichtlinie
10.1 Es werden keine personenbezogenen Daten von Benutzern erhoben.
10.2 Alle Informationen über Partien, Statistiken und Einstellungen werden nur im LocalStorage Ihres Browsers gespeichert.
10.3 Es werden unter keinen Umständen Informationen mit Dritten geteilt.
10.4 Die Anwendung führt kein Tracking durch und verwendet keine externen Cookies; alle verwendeten Cookies dienen ausschließlich dem internen Betrieb.

11. Anwendbares Recht und Gerichtsstand
11.1 Diese Bedingungen unterliegen dem Recht der Republik Paraguay.
11.2 Alle Rechtsstreitigkeiten im Zusammenhang mit der Anwendung werden ausschließlich vor den Gerichten von Asunción, Paraguay, beigelegt.

12. Kontakt
Bei Fragen zu diesen Bedingungen können Sie uns unter folgender Adresse kontaktieren: [dinerocor@hotmail.com]

Durch die Nutzung von Strategix akzeptieren Sie diese Allgemeinen Geschäftsbedingungen und unsere Datenschutzrichtlinie in vollem Umfang, mit der Zusicherung, dass keine personenbezogenen Daten außerhalb Ihres Geräts erhoben oder übertragen werden.`,
      agree: 'Ich habe die Allgemeinen Geschäftsbedingungen gelesen und stimme ihnen zu.',
      accept: 'Akzeptieren',
    },
    common: {
        back: 'Zurück',
        cancel: 'Abbrechen',
        comingSoon: 'Kommt bald',
    }
  },
  pt: {
    mainMenu: {
      title: 'Strategix',
      play: 'Jogar Xadrez',
      load: 'Carregar Jogo',
      stats: 'Estatísticas',
      settings: 'Configurações',
      help: 'Ajuda / Tutorial',
      exit: 'Sair',
    },
    playMenu: {
        title: 'Jogar Xadrez',
        vsAI: 'vs. IA',
        local: 'vs. Humano',
        tutorial: 'Treino / Tutorial',
        difficulty: 'Dificuldade',
        easy: 'Fácil',
        medium: 'Médio',
        hard: 'Difícil',
        master: 'Mestre',
        easyDesc: 'Um jogo casual, bom para aprender.',
        mediumDesc: 'Um desafio equilibrado para a maioria dos jogadores.',
        hardDesc: 'Um oponente difícil que pune erros.',
        masterDesc: 'Desafio máximo. Joga lances quase ideais.',
        pieceColor: 'Cor das Peças',
        white: 'Brancas',
        black: 'Pretas',
        random: 'Aleatório',
        moveHints: 'Dicas de Lances',
        start: 'Começar Jogo',
        onlineComingSoon: 'Modo Online - Em breve',
    },
    loadMenu: {
        title: 'Carregar Jogo',
        empty: 'Nenhum jogo salvo encontrado.',
        load: 'Carregar',
        delete: 'Excluir',
    },
    statsMenu: {
        title: 'Estatísticas',
        totalGames: 'Total de Jogos',
        wins: 'Vitórias',
        losses: 'Derrotas',
        draws: 'Empates',
        rating: 'Rating Offline',
        winLossRatio: 'Relação Vitória/Derrota',
        mostUsedOpenings: 'Aberturas Mais Usadas',
    },
    settingsMenu: {
        title: 'Configurações',
        language: 'Idioma',
        sound: 'Som',
        music: 'Música',
        on: 'Ligado',
        off: 'Desligado',
        theme: 'Tema do Tabuleiro',
        light: 'Claro',
        dark: 'Escuro',
        animationSpeed: 'Velocidade da Animação',
        fast: 'Rápida',
        normal: 'Normal',
        slow: 'Lenta',
        resetStats: 'Redefinir Estatísticas',
        resetConfirm: 'Tem certeza de que deseja redefinir todas as estatísticas? Isso não pode ser desfeito.',
        confirm: 'Confirmar',
    },
    helpMenu: {
        title: 'Ajuda / Tutorial',
        rules: 'Regras Básicas (FIDE)',
        pawn: 'Peão: Move uma casa para frente, mas duas em seu primeiro movimento. Captura na diagonal.',
        knight: 'Cavalo: Move-se em forma de "L" (duas casas em uma direção, depois uma perpendicularmente).',
        bishop: 'Bispo: Move-se diagonalmente qualquer número de casas.',
        rook: 'Torre: Move-se horizontalmente ou verticalmente qualquer número de casas.',
        queen: 'Dama: Combina o poder da torre e do bispo.',
        king: 'Rei: Move uma casa em qualquer direção.',
        faq: 'FAQ',
        faq1_q: 'Este aplicativo é 100% offline?',
        faq1_a: 'Sim, todos os recursos são projetados para funcionar sem conexão com a internet.',
        viewTerms: 'Ver Termos e Condições',
    },
    termsModal: {
      title: 'Termos e Condições',
      content: `TERMOS E CONDIÇÕES E POLÍTICA DE PRIVACIDADE DA STRATEGIX

Última atualização: 21 de setembro de 2025

1. Introdução
Bem-vindo ao Strategix, um aplicativo web de xadrez 100% offline. Ao acessar ou usar o Strategix, você concorda em ficar vinculado a estes Termos e Condições e à nossa Política de Privacidade. Se você не concorda com algum destes termos, não use o aplicativo.

2. Propriedade e Créditos
O Strategix é propriedade da Benzanox Studios. Embora a IA Gemini 2.5 Pro tenha sido usada para o desenvolvimento, todos os direitos de propriedade intelectual do aplicativo pertencem a você como proprietário do aplicativo.

3. Uso do Aplicativo
3.1 O Strategix é um aplicativo destinado a fins de entretenimento e aprendizado de xadrez.
3.2 Você concorda em não usar o aplicativo para atividades ilegais, incluindo pirataria, hacking ou violação dos direitos de terceiros.
3.3 O aplicativo funciona completamente offline e не coleta dados externos.

4. Conteúdo do Usuário e Armazenamento
4.1 Todos os dados gerados por você, incluindo jogos e configurações, são mantidos exclusivamente no LocalStorage do seu dispositivo.
4.2 O Strategix не coleta, transmite ou compartilha dados pessoais ou de jogos com servidores externos.
4.3 Você é responsável por manter a segurança do seu dispositivo e dos dados armazenados localmente.

5. Licença de Uso
5.1 É concedida a você uma licença limitada, não exclusiva e intransferível para usar o Strategix em seu navegador.
5.2 Não é permitido redistribuir, vender, descompilar ou criar trabalhos derivados do aplicativo sem autorização expressa.

6. Propriedade Intelectual
6.1 Todos os direitos autorais, marcas registradas e designs gráficos do Strategix, incluindo as peças de xadrez e a interface, são propriedade da Benzanox Studios.
6.2 O usuário não adquire direitos de propriedade intelectual ao usar o aplicativo.

7. Limitação de Responsabilidade
7.1 O Strategix é fornecido "como está" e не garante que o aplicativo estará livre de erros ou interrupções.
7.2 A Benzanox Studios не será responsável por quaisquer danos diretos, indiretos, incidentais ou consequenciais decorrentes do uso do aplicativo.

8. Modificações e Atualizações
8.1 A Benzanox Studios pode atualizar ou modificar o Strategix e estes termos a qualquer momento.
8.2 Recomenda-se revisar esta seção periodicamente. O uso contínuo implica a aceitação das alterações.

9. Responsabilidade do Usuário
9.1 O usuário é responsável pelo uso adequado do aplicativo e pela manutenção segura de seus dados locais.
9.2 Recomenda-se fazer backups de jogos e configurações importantes para evitar a perda de informações devido a falhas no dispositivo.
9.3 Qualquer uso indevido que cause danos a terceiros é de responsabilidade exclusiva do usuário.

10. Política de Privacidade
10.1 Nenhum dado pessoal é coletado dos usuários.
10.2 Todas as informações sobre jogos, estatísticas e configurações são armazenadas apenas no LocalStorage do seu navegador.
10.3 Nenhuma informação é compartilhada com terceiros sob nenhuma circunstância.
10.4 O aplicativo não realiza rastreamento nem utiliza cookies externos; quaisquer cookies utilizados são estritamente para operação interna.

11. Lei Aplicável e Jurisdição
11.1 Estes termos são regidos pela Lei da República do Paraguai.
11.2 Qualquer disputa legal relacionada ao aplicativo será resolvida exclusivamente nos tribunais de Assunção, Paraguai.

12. Contato
Para perguntas sobre estes termos, você pode nos contatar em: [dinerocor@hotmail.com]

Ao usar o Strategix, você aceita estes Termos e Condições e nossa Política de Privacidade em sua totalidade, com a garantia de que nenhum dado pessoal é coletado ou transmitido para fora do seu dispositivo.`,
      agree: 'Li e concordo com os termos e condições.',
      accept: 'Aceitar',
    },
    common: {
        back: 'Voltar',
        cancel: 'Cancelar',
        comingSoon: 'Em breve',
    }
  },
  ru: {
    mainMenu: {
      title: 'Strategix',
      play: 'Играть в шахматы',
      load: 'Загрузить игру',
      stats: 'Статистика',
      settings: 'Настройки',
      help: 'Помощь / Обучение',
      exit: 'Выход',
    },
    playMenu: {
        title: 'Играть в шахматы',
        vsAI: 'против ИИ',
        local: 'против Человека',
        tutorial: 'Тренировка / Обучение',
        difficulty: 'Сложность',
        easy: 'Легко',
        medium: 'Средне',
        hard: 'Сложно',
        master: 'Мастер',
        easyDesc: 'Обычная игра, хороша для обучения.',
        mediumDesc: 'Сбалансированный вызов для большинства игроков.',
        hardDesc: 'Сильный противник, наказывающий за ошибки.',
        masterDesc: 'Максимальная сложность. Играет почти оптимальные ходы.',
        pieceColor: 'Цвет фигур',
        white: 'Белые',
        black: 'Черные',
        random: 'Случайно',
        moveHints: 'Подсказки ходов',
        start: 'Начать игру',
        onlineComingSoon: 'Онлайн-режим - Скоро',
    },
    loadMenu: {
        title: 'Загрузить игру',
        empty: 'Сохраненных игр не найдено.',
        load: 'Загрузить',
        delete: 'Удалить',
    },
    statsMenu: {
        title: 'Статистика',
        totalGames: 'Всего игр',
        wins: 'Победы',
        losses: 'Поражения',
        draws: 'Ничьи',
        rating: 'Офлайн-рейтинг',
        winLossRatio: 'Соотношение побед/поражений',
        mostUsedOpenings: 'Самые используемые дебюты',
    },
    settingsMenu: {
        title: 'Настройки',
        language: 'Язык',
        sound: 'Звук',
        music: 'Музыка',
        on: 'Вкл',
        off: 'Выкл',
        theme: 'Тема доски',
        light: 'Светлая',
        dark: 'Темная',
        animationSpeed: 'Скорость анимации',
        fast: 'Быстро',
        normal: 'Нормально',
        slow: 'Медленно',
        resetStats: 'Сбросить статистику',
        resetConfirm: 'Вы уверены, что хотите сбросить всю статистику? Это действие нельзя отменить.',
        confirm: 'Подтвердить',
    },
    helpMenu: {
        title: 'Помощь / Обучение',
        rules: 'Основные правила (FIDE)',
        pawn: 'Пешка: Двигается на одну клетку вперед, но на две на первом ходу. Бьет по диагонали.',
        knight: 'Конь: Двигается буквой "Г" (две клетки в одном направлении, затем одна перпендикулярно).',
        bishop: 'Слон: Двигается по диагонали на любое количество клеток.',
        rook: 'Ладья: Двигается по горизонтали или вертикали на любое количество клеток.',
        queen: 'Ферзь: Сочетает в себе силу ладьи и слона.',
        king: 'Король: Двигается на одну клетку в любом направлении.',
        faq: 'ЧаВо',
        faq1_q: 'Это приложение на 100% офлайн?',
        faq1_a: 'Да, все функции разработаны для работы без подключения к интернету.',
        viewTerms: 'Просмотреть Условия и положения',
    },
    termsModal: {
      title: 'Условия и положения',
      content: `УСЛОВИЯ И ПОЛОЖЕНИЯ И ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ STRATEGIX

Последнее обновление: 21 сентября 2025 г.

1. Введение
Добро пожаловать в Strategix, 100% оффлайн веб-приложение для игры в шахматы. Получая доступ к Strategix или используя его, вы соглашаетесь соблюдать настоящие Условия и положения и нашу Политику конфиденциальности. Если вы не согласны с каким-либо из этих условий, не используйте приложение.

2. Собственность и авторы
Strategix принадлежит Benzanox Studios. Хотя для разработки использовался ИИ Gemini 2.5 Pro, все права на интеллектуальную собственность приложения принадлежат вам как владельцу приложения.

3. Использование приложения
3.1 Strategix - это приложение, предназначенное для развлечения и обучения игре в шахматы.
3.2 Вы соглашаетесь не использовать приложение для незаконной деятельности, включая пиратство, взлом или нарушение прав третьих лиц.
3.3 Приложение работает полностью в автономном режиме и не собирает никаких внешних данных.

4. Пользовательский контент и хранение
4.1 Все данные, созданные вами, включая игры и настройки, хранятся исключительно в LocalStorage вашего устройства.
4.2 Strategix не собирает, не передает и не делится личными или игровыми данными с внешними серверами.
4.3 Вы несете ответственность за обеспечение безопасности вашего устройства и данных, хранящихся локально.

5. Лицензия на использование
5.1 Вам предоставляется ограниченная, неисключительная, непередаваемая лицензия на использование Strategix в вашем браузere.
5.2 Запрещается распространять, продавать, декомпилировать или создавать производные работы на основе приложения без специального разрешения.

6. Интеллектуальная собственность
6.1 Все авторские права, товарные знаки и графические дизайны Strategix, включая шахматные фигуры и интерфейс, являются собственностью Benzanox Studios.
6.2 Пользователь не приобретает никаких прав на интеллектуальную собственность при использовании приложения.

7. Ограничение ответственности
7.1 Strategix предоставляется «как есть» и не гарантирует, что приложение будет работать без ошибок или перебоев.
7.2 Benzanox Studios не несет ответственности за любые прямые, косвенные, случайные или последующие убытки, возникшие в результате использования приложения.

8. Изменения и обновления
8.1 Benzanox Studios может обновлять или изменять Strategix и настоящие условия в любое время.
8.2 Рекомендуется периодически просматривать этот раздел. Продолжение использования означает принятие изменений.

9. Ответственность пользователя
9.1 Пользователь несет ответственность за надлежащее использование приложения и за безопасное хранение своих локальных данных.
9.2 Рекомендуется делать резервные копии важных игр и настроек, чтобы избежать потери информации из-за сбоев устройства.
9.3 Любое неправомерное использование, причиняющее ущерб третьим лицам, является исключительной ответственностью пользователя.

10. Политика конфиденциальности
10.1 Личные данные пользователей не собираются.
10.2 Вся информация об играх, статистике и настройках хранится только в LocalStorage вашего браузера.
10.3 Информация не передается третьим лицам ни при каких обстоятельствах.
10.4 Приложение не отслеживает и не использует внешние файлы cookie; любые используемые файлы cookie предназначены исключительно для внутренней работы.

11. Применимое право и юрисдикция
11.1 Настоящие условия регулируются законодательством Республики Парагвай.
11.2 Любые юридические споры, связанные с приложением, будут разрешаться исключительно в судах Асунсьона, Парагвай.

12. Контакты
По вопросам, касающимся этих условий, вы можете связаться с нами по адресу: [dinerocor@hotmail.com]

Используя Strategix, вы полностью принимаете настоящие Условия и положения и нашу Политику конфиденциальности, с уверенностью в том, что никакие личные данные не собираются и не передаются за пределы вашего устройства.`,
      agree: 'Я прочитал и согласен с условиями и положениями.',
      accept: 'Принять',
    },
    common: {
        back: 'Назад',
        cancel: 'Отмена',
        comingSoon: 'Скоро',
    }
  },
  zh: {
    mainMenu: {
      title: 'Strategix',
      play: '开始游戏',
      load: '加载游戏',
      stats: '统计数据',
      settings: '设置',
      help: '帮助 / 教程',
      exit: '退出',
    },
    playMenu: {
        title: '开始游戏',
        vsAI: '对战 AI',
        local: '本地双人',
        tutorial: '训练 / 教程',
        difficulty: '难度',
        easy: '简单',
        medium: '中等',
        hard: '困难',
        master: '大师',
        easyDesc: '休闲游戏，适合学习。',
        mediumDesc: '为多数玩家提供均衡的挑战。',
        hardDesc: '一个会惩罚错误的强硬对手。',
        masterDesc: '最高挑战。走出近乎最佳的棋步。',
        pieceColor: '棋子颜色',
        white: '白方',
        black: '黑方',
        random: '随机',
        moveHints: '走法提示',
        start: '开始游戏',
        onlineComingSoon: '在线模式 - 敬请期待',
    },
    loadMenu: {
        title: '加载游戏',
        empty: '未找到已保存的游戏。',
        load: '加载',
        delete: '删除',
    },
    statsMenu: {
        title: '统计数据',
        totalGames: '总局数',
        wins: '胜',
        losses: '负',
        draws: '平',
        rating: '离线积分',
        winLossRatio: '胜/负比',
        mostUsedOpenings: '最常用开局',
    },
    settingsMenu: {
        title: '设置',
        language: '语言',
        sound: '声音',
        music: '音乐',
        on: '开',
        off: '关',
        theme: '棋盘主题',
        light: '浅色',
        dark: '深色',
        animationSpeed: '动画速度',
        fast: '快',
        normal: '正常',
        slow: '慢',
        resetStats: '重置统计数据',
        resetConfirm: '您确定要重置所有统计数据吗？此操作无法撤销。',
        confirm: '确认',
    },
    helpMenu: {
        title: '帮助 / 教程',
        rules: '基本规则 (FIDE)',
        pawn: '兵：向前走一格，但第一次可以走两格。斜向吃子。',
        knight: '马：走“日”字（在一个方向上走两格，然后垂直走一格）。',
        bishop: '象：沿斜线走任意格数。',
        rook: '车：沿横线或竖线走任意格数。',
        queen: '后：结合了车和象的力量。',
        king: '王：向任何方向走一格。',
        faq: '常见问题',
        faq1_q: '这个应用是 100% 离线的吗？',
        faq1_a: '是的，所有功能都设计为在没有网络连接的情况下工作。',
        viewTerms: '查看条款和条件',
    },
    termsModal: {
      title: '条款和条件',
      content: `STRATEGIX 条款和条件及隐私政策

最后更新：2025年9月21日

1. 介绍
欢迎使用 Strategix，一个100%离线的国际象棋网页应用。访问或使用 Strategix，即表示您同意受这些条款和条件及我们的隐私政策的约束。如果您不同意这些条款中的任何一项，请不要使用该应用程序。

2. 所有权和鸣谢
Strategix 归 Benzanox Studios 所有。尽管开发过程中使用了 Gemini 2.5 Pro AI，但该应用程序的所有知识产权均属于您（作为应用程序所有者）。

3. 应用程序的使用
3.1 Strategix 是一款用于娱乐和国际象棋学习的应用程序。
3.2 您同意不将该应用程序用于非法活动，包括盗版、黑客攻击或侵犯第三方权利。
3.3 该应用程序完全离线运行，不收集任何外部数据。

4. 用户内容和存储
4.1 您生成的所有数据，包括游戏和设置，都专门保存在您设备的 LocalStorage 中。
4.2 Strategix 不会与外部服务器收集、传输或共享个人或游戏数据。
4.3 您有责任维护您的设备和本地存储数据的安全。

5. 使用许可
5.1 您被授予在浏览器中使用 Strategix 的有限、非独占、不可转让的许可。
5.2 未经明确授权，不得重新分发、销售、反编译或创建该应用程序的衍生作品。

6. 知识产权
6.1 Strategix 的所有版权、商标和图形设计，包括棋子和界面，均为 Benzanox Studios 的财产。
6.2 用户通过使用该应用程序不获得任何知识产权。

7. 责任限制
7.1 Strategix 按“原样”提供，不保证该应用程序没有错误或中断。
7.2 Benzanox Studios 对因使用该应用程序而产生的任何直接、间接、偶然或后果性损害概不负责。

8. 修改和更新
8.1 Benzanox Studios 可随时更新或修改 Strategix 和这些条款。
8.2 建议定期查看此部分。继续使用即表示接受更改。

9. 用户责任
9.1 用户有责任正确使用该应用程序并安全维护其本地数据。
9.2 建议备份重要的游戏和设置，以避免因设备故障导致信息丢失。
9.3 任何对第三方造成损害的滥用行为均由用户自行承担责任。

10. 隐私政策
10.1 不收集用户的个人数据。
10.2 有关游戏、统计和设置的所有信息仅存储在您浏览器的 LocalStorage 中。
10.3 在任何情况下都不会与第三方共享信息。
10.4 该应用程序不执行跟踪或使用外部 cookie；任何使用的 cookie 均严格用于内部操作。

11. 适用法律和司法管辖权
11.1 这些条款受巴拉圭共和国法律管辖。
11.2 与该应用程序相关的任何法律争议将专门在巴拉圭亚松森的法院解决。

12. 联系方式
有关这些条款的问题，您可以通过以下方式联系我们：[dinerocor@hotmail.com]

使用 Strategix，即表示您完全接受这些条款和条件及我们的隐私政策，并保证不会在您的设备之外收集或传输任何个人数据。`,
      agree: '我已阅读并同意条款和条件。',
      accept: '接受',
    },
    common: {
        back: '返回',
        cancel: '取消',
        comingSoon: '敬请期待',
    }
  },
  ja: {
    mainMenu: {
      title: 'Strategix',
      play: 'チェスをプレイ',
      load: 'ゲームをロード',
      stats: '統計',
      settings: '設定',
      help: 'ヘルプ / チュートorial',
      exit: '終了',
    },
    playMenu: {
        title: 'チェスをプレイ',
        vsAI: 'vs. AI',
        local: 'vs. 人間',
        tutorial: 'トレーニング / チュートorial',
        difficulty: '難易度',
        easy: '簡単',
        medium: '普通',
        hard: '難しい',
        master: 'マスター',
        easyDesc: '学習に適したカジュアルなゲームです。',
        mediumDesc: 'ほとんどのプレイヤーにとってバランスの取れた挑戦です。',
        hardDesc: 'ミスを罰する手ごわい相手です。',
        masterDesc: '最大の挑戦。ほぼ最適な手を指します。',
        pieceColor: '駒の色',
        white: '白',
        black: '黒',
        random: 'ランダム',
        moveHints: 'ヒント',
        start: 'ゲーム開始',
        onlineComingSoon: 'オンラインモード - 近日公開',
    },
    loadMenu: {
        title: 'ゲームをロード',
        empty: '保存されたゲームが見つかりません。',
        load: 'ロード',
        delete: '削除',
    },
    statsMenu: {
        title: '統計',
        totalGames: '合計ゲーム数',
        wins: '勝利',
        losses: '敗北',
        draws: '引き分け',
        rating: 'オフラインレーティング',
        winLossRatio: '勝敗率',
        mostUsedOpenings: '最も使われたオープニング',
    },
    settingsMenu: {
        title: '設定',
        language: '言語',
        sound: 'サウンド',
        music: '音楽',
        on: 'オン',
        off: 'オフ',
        theme: 'ボードのテーマ',
        light: 'ライト',
        dark: 'ダーク',
        animationSpeed: 'アニメーション速度',
        fast: '速い',
        normal: '普通',
        slow: '遅い',
        resetStats: '統計をリセット',
        resetConfirm: '本当にすべての統計をリセットしますか？この操作は元に戻せません。',
        confirm: '確認',
    },
    helpMenu: {
        title: 'ヘルプ / チュートorial',
        rules: '基本ルール (FIDE)',
        pawn: 'ポーン：前方に1マス、最初の動きでは2マス進む。斜めに取る。',
        knight: 'ナイト：「L」字型に動く（一方向に2マス、次に垂直に1マス）。',
        bishop: 'ビショップ：斜めに何マスでも動く。',
        rook: 'ルーク：水平または垂直に何マスでも動く。',
        queen: 'クイーン：ルークとビショップの力を組み合わせる。',
        king: 'キング：どの方向にも1マス動く。',
        faq: 'FAQ',
        faq1_q: 'このアプリは100%オフラインですか？',
        faq1_a: 'はい、すべての機能はインターネット接続なしで動作するように設計されています。',
        viewTerms: '利用規約を表示',
    },
    termsModal: {
      title: '利用規約',
      content: `STRATEGIX 利用規約およびプライバシーポリシー

最終更新日：2025年9月21日

1. はじめに
Strategixへようこそ。これは100％オフラインのチェスウェブアプリケーションです。Strategixにアクセスまたは使用することにより、お客様はこれらの利用規約および当社のプライバシーポリシーに拘束されることに同意したものとします。これらの利用規約のいずれかに同意しない場合は、アプリケーションを使用しないでください。

2. 所有権とクレジット
StrategixはBenzanox Studiosが所有しています。開発にはGemini 2.5 Pro AIが使用されましたが、アプリのすべての知的財産権はアプリの所有者であるあなたに帰属します。

3. アプリケーションの利用
3.1 Strategixは、エンターテイメントおよびチェス学習を目的としたアプリケーションです。
3.2 お客様は、著作権侵害、ハッキング、第三者の権利侵害などの違法行為にアプリケーションを使用しないことに同意するものとします。
3.3 アプリケーションは完全にオフラインで実行され、外部データを収集しません。

4. ユーザーコンテンツとストレージ
4.1 ゲームや設定を含む、お客様が生成したすべてのデータは、お客様のデバイスのLocalStorageにのみ保存されます。
4.2 Strategixは、個人データやゲームデータを外部サーバーと収集、送信、共有することはありません。
4.3 お客様は、ご自身のデバイスとローカルに保存されたデータのセキュリティを維持する責任があります。

5. 利用ライセンス
5.1 お客様には、お使いのブラウザでStrategixを使用するための限定的、非独占的、譲渡不可能なライセンスが付与されます。
5.2 明示的な許可なく、アプリケーションを再配布、販売、逆コンパイル、または派生物を作成することは許可されていません。

6. 知的財産
6.1 チェスの駒やインターフェースを含む、Strategixのすべての著作権、商標、グラフィックデザインはBenzanox Studiosの財産です。
6.2 ユーザーは、アプリケーションを使用することによって知的財産権を取得することはありません。

7. 責任の制限
7.1 Strategixは「現状有姿」で提供され、アプリケーションにエラーや中断がないことを保証するものではありません。
7.2 Benzanox Studiosは、アプリケーションの使用から生じるいかなる直接的、間接的、付随的、または結果的な損害についても責任を負いません。

8. 変更と更新
8.1 Benzanox Studiosは、いつでもStrategixおよびこれらの利用規約を更新または変更することがあります。
8.2 このセクションを定期的に確認することをお勧めします。継続的な使用は、変更を承諾したものとみなされます。

9. ユーザーの責任
9.1 ユーザーは、アプリケーションの適切な使用とローカルデータの安全な管理に責任を負います。
9.2 デバイスの故障による情報損失を避けるため、重要なゲームや設定のバックアップを作成することをお勧めします。
9.3 第三者に損害を与えるような誤用は、すべてユーザーの責任となります。

10. プライバシーポリシー
10.1 ユーザーから個人データを収集することはありません。
10.2 ゲーム、統計、設定に関するすべての情報は、お使いのブラウザのLocalStorageにのみ保存されます。
10.3 いかなる状況においても、第三者と情報を共有することはありません。
10.4 アプリケーションは追跡や外部Cookieの使用を行いません。使用されるCookieは、厳密に内部操作のためのものです。

11. 準拠法および裁判管轄
11.1 これらの利用規約は、パラグアイ共和国の法律に準拠します。
11.2 アプリケーションに関連する法的紛争は、パラグアイのアスンシオンの裁判所で専属的に解決されるものとします。

12. お問い合わせ
これらの利用規約に関するご質問は、[dinerocor@hotmail.com]までお問い合わせください。

Strategixを使用することにより、お客様はこれらの利用規約および当社のプライバシーポリシーに完全に同意したことになり、個人データがお客様のデバイス外で収集または送信されることはないことを保証します。`,
      agree: '利用規約を読み、同意します。',
      accept: '同意する',
    },
    common: {
        back: '戻る',
        cancel: 'キャンセル',
        comingSoon: '近日公開',
    }
  },
  ko: {
    mainMenu: {
      title: 'Strategix',
      play: '체스하기',
      load: '게임 불러오기',
      stats: '통계',
      settings: '설정',
      help: '도움말 / 튜토리얼',
      exit: '종료',
    },
    playMenu: {
        title: '체스하기',
        vsAI: 'vs. AI',
        local: 'vs. 사람',
        tutorial: '훈련 / 튜토리얼',
        difficulty: '난이도',
        easy: '쉬움',
        medium: '중간',
        hard: '어려움',
        master: '마스터',
        easyDesc: '배우기 좋은 캐주얼 게임입니다.',
        mediumDesc: '대부분의 플레이어에게 균형 잡힌 도전입니다.',
        hardDesc: '실수를 응징하는 힘든 상대입니다.',
        masterDesc: '최고의 도전. 거의 최적의 수를 둡니다.',
        pieceColor: '기물 색상',
        white: '백',
        black: '흑',
        random: '무작위',
        moveHints: '수 힌트',
        start: '게임 시작',
        onlineComingSoon: '온라인 모드 - 출시 예정',
    },
    loadMenu: {
        title: '게임 불러오기',
        empty: '저장된 게임이 없습니다.',
        load: '불러오기',
        delete: '삭제',
    },
    statsMenu: {
        title: '통계',
        totalGames: '총 게임 수',
        wins: '승',
        losses: '패',
        draws: '무',
        rating: '오프라인 레이팅',
        winLossRatio: '승/패 비율',
        mostUsedOpenings: '가장 많이 사용된 오프닝',
    },
    settingsMenu: {
        title: '설정',
        language: '언어',
        sound: '소리',
        music: '음악',
        on: '켜기',
        off: '끄기',
        theme: '보드 테마',
        light: '밝게',
        dark: '어둡게',
        animationSpeed: '애니메이션 속도',
        fast: '빠름',
        normal: '보통',
        slow: '느림',
        resetStats: '통계 초기화',
        resetConfirm: '모든 통계를 초기화하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
        confirm: '확인',
    },
    helpMenu: {
        title: '도움말 / 튜토리얼',
        rules: '기본 규칙 (FIDE)',
        pawn: '폰: 앞으로 한 칸 이동하지만, 첫 수에는 두 칸 이동 가능. 대각선으로 잡습니다.',
        knight: '나이트: "L"자 형태로 이동 (한 방향으로 두 칸, 그 다음 수직으로 한 칸).',
        bishop: '비숍: 대각선으로 원하는 만큼 이동합니다.',
        rook: '룩: 가로 또는 세로로 원하는 만큼 이동합니다.',
        queen: '퀸: 룩과 비숍의 힘을 합쳤습니다.',
        king: '킹: 모든 방향으로 한 칸 이동합니다.',
        faq: '자주 묻는 질문',
        faq1_q: '이 앱은 100% 오프라인인가요?',
        faq1_a: '예, 모든 기능은 인터넷 연결 없이 작동하도록 설계되었습니다.',
        viewTerms: '이용약관 보기',
    },
    termsModal: {
      title: '이용약관',
      content: `STRATEGIX 이용 약관 및 개인정보 보호정책

최종 업데이트: 2025년 9월 21일

1. 소개
100% 오프라인 체스 웹 애플리케이션인 Strategix에 오신 것을 환영합니다. Strategix에 접속하거나 사용함으로써 귀하는 본 이용 약관 및 개인정보 보호정책에 동의하는 것으로 간주됩니다. 본 약관의 내용에 동의하지 않는 경우 애플리케이션을 사용하지 마십시오.

2. 소유권 및 크레딧
Strategix는 Benzanox Studios의 소유입니다. 개발에 Gemini 2.5 Pro AI가 사용되었지만 앱의 모든 지적 재산권은 앱 소유자인 귀하에게 있습니다.

3. 애플리케이션 사용
3.1 Strategix는 오락 및 체스 학습을 목적으로 하는 애플리케이션입니다.
3.2 귀하는 불법 복제, 해킹 또는 제3자의 권리 침해를 포함한 불법 활동에 애플리케이션을 사용하지 않을 것에 동의합니다.
3.3 이 애플리케이션은 완전히 오프라인으로 실행되며 외부 데이터를 수집하지 않습니다.

4. 사용자 콘텐츠 및 저장
4.1 게임 및 설정을 포함하여 귀하가 생성한 모든 데이터는 귀하의 장치 LocalStorage에만 보관됩니다.
4.2 Strategix는 개인 또는 게임 데이터를 외부 서버와 수집, 전송 또는 공유하지 않습니다.
4.3 귀하는 귀하의 장치 및 로컬에 저장된 데이터의 보안을 유지할 책임이 있습니다.

5. 사용 라이선스
5.1 귀하에게는 브라우저에서 Strategix를 사용할 수 있는 제한적이고 비독점적이며 양도 불가능한 라이선스가 부여됩니다.
5.2 명시적인 허가 없이 애플리케이션을 재배포, 판매, 디컴파일 또는 파생물을 생성하는 것은 허용되지 않습니다.

6. 지적 재산
6.1 체스 말 및 인터페이스를 포함한 Strategix의 모든 저작권, 상표 및 그래픽 디자인은 Benzanox Studios의 자산입니다.
6.2 사용자는 애플리케이션을 사용함으로써 어떠한 지적 재산권도 취득하지 않습니다.

7. 책임의 제한
7.1 Strategix는 "있는 그대로" 제공되며 애플리케이션에 오류나 중단이 없음을 보장하지 않습니다.
7.2 Benzanox Studios는 애플리케이션 사용으로 인해 발생하는 직접적, 간접적, 부수적 또는 결과적 손해에 대해 책임을 지지 않습니다.

8. 수정 및 업데이트
8.1 Benzanox Studios는 언제든지 Strategix와 본 약관을 업데이트하거나 수정할 수 있습니다.
8.2 이 섹션을 주기적으로 검토하는 것이 좋습니다. 계속 사용하면 변경 사항에 동의하는 것으로 간주됩니다.

9. 사용자 책임
9.1 사용자는 애플리케이션의 올바른 사용과 로컬 데이터의 안전한 유지 관리에 대한 책임이 있습니다.
9.2 장치 오류로 인한 정보 손실을 방지하기 위해 중요한 게임 및 설정을 백업하는 것이 좋습니다.
9.3 제3자에게 손해를 끼치는 모든 오용은 전적으로 사용자의 책임입니다.

10. 개인정보 보호정책
10.1 사용자로부터 개인 데이터를 수집하지 않습니다.
10.2 게임, 통계 및 설정에 대한 모든 정보는 브라우저의 LocalStorage에만 저장됩니다.
10.3 어떠한 경우에도 제3자와 정보를 공유하지 않습니다.
10.4 애플리케이션은 추적이나 외부 쿠키 사용을 수행하지 않으며, 사용되는 모든 쿠키는 엄격하게 내부 작동을 위한 것입니다.

11. 준거법 및 관할권
11.1 본 약관은 파라과이 공화국 법률의 적용을 받습니다.
11.2 애플리케이션과 관련된 모든 법적 분쟁은 파라과이 아순시온 법원에서 독점적으로 해결됩니다.

12. 연락처
본 약관에 대한 질문은 [dinerocor@hotmail.com]으로 문의하십시오.

Strategix를 사용함으로써 귀하는 본 이용 약관 및 개인정보 보호정책 전체에 동의하며, 개인 데이터가 귀하의 장치 외부에서 수집되거나 전송되지 않음을 보증합니다。`,
      agree: '이용약관을 읽고 동의합니다.',
      accept: '동의',
    },
    common: {
        back: '뒤로',
        cancel: '취소',
        comingSoon: '출시 예정',
    }
  },
  ar: {
    mainMenu: {
      title: 'Strategix',
      play: 'العب شطرنج',
      load: 'تحميل لعبة',
      stats: 'الإحصائيات',
      settings: 'الإعدادات',
      help: 'مساعدة / تعليمي',
      exit: 'خروج',
    },
    playMenu: {
        title: 'العب شطرنج',
        vsAI: 'ضد الذكاء الاصطناعي',
        local: 'ضد لاعب آخر',
        tutorial: 'تدريب / تعليمي',
        difficulty: 'الصعوبة',
        easy: 'سهل',
        medium: 'متوسط',
        hard: 'صعب',
        master: 'محترف',
        easyDesc: 'لعبة عادية، جيدة للتعلم.',
        mediumDesc: 'تحد متوازن لمعظم اللاعبين.',
        hardDesc: 'خصم قوي يعاقب على الأخطاء.',
        masterDesc: 'تحد أقصى. يلعب نقلات شبه مثالية.',
        pieceColor: 'لون القطع',
        white: 'أبيض',
        black: 'أسود',
        random: 'عشوائي',
        moveHints: 'تلميحات النقلة',
        start: 'ابدأ اللعبة',
        onlineComingSoon: 'وضع الأونلاين - قريباً',
    },
    loadMenu: {
        title: 'تحميل لعبة',
        empty: 'لا توجد ألعاب محفوظة.',
        load: 'تحميل',
        delete: 'حذف',
    },
    statsMenu: {
        title: 'الإحصائيات',
        totalGames: 'إجمالي الألعاب',
        wins: 'فوز',
        losses: 'خسارة',
        draws: 'تعادل',
        rating: 'التقييم بدون اتصال',
        winLossRatio: 'نسبة الفوز/الخسارة',
        mostUsedOpenings: 'الافتتاحيات الأكثر استخدامًا',
    },
    settingsMenu: {
        title: 'الإعدادات',
        language: 'اللغة',
        sound: 'الصوت',
        music: 'موسيقى',
        on: 'تشغيل',
        off: 'إيقاف',
        theme: 'سمة اللوحة',
        light: 'فاتح',
        dark: 'داكن',
        animationSpeed: 'سرعة الحركة',
        fast: 'سريع',
        normal: 'عادي',
        slow: 'بطيء',
        resetStats: 'إعادة تعيين الإحصائيات',
        resetConfirm: 'هل أنت متأكد أنك تريد إعادة تعيين جميع الإحصائيات؟ لا يمكن التراجع عن هذا الإجراء.',
        confirm: 'تأكيد',
    },
    helpMenu: {
        title: 'مساعدة / تعليمي',
        rules: 'القواعد الأساسية (FIDE)',
        pawn: 'البيدق: يتحرك مربعًا واحدًا للأمام، ولكن مربعين في حركته الأولى. يأسر قطريًا.',
        knight: 'الحصان: يتحرك على شكل "L" (مربعان في اتجاه واحد، ثم واحد بشكل عمودي).',
        bishop: 'الفيل: يتحرك قطريًا أي عدد من المربعات.',
        rook: 'القلعة: تتحرك أفقيًا أو رأسيًا أي عدد من المربعات.',
        queen: 'الوزير: يجمع بين قوة القلعة والفيل.',
        king: 'الملك: يتحرك مربعًا واحدًا في أي اتجاه.',
        faq: 'الأسئلة الشائعة',
        faq1_q: 'هل هذا التطبيق يعمل 100٪ بدون اتصال بالإنترنت؟',
        faq1_a: 'نعم، جميع الميزات مصممة للعمل بدون اتصال بالإنترنت.',
        viewTerms: 'عرض الشروط والأحكام',
    },
    termsModal: {
      title: 'الشروط والأحكام',
      content: `شروط وأحكام وسياسة خصوصية STRATEGIX

آخر تحديث: 21 سبتمبر 2025

1. مقدمة
مرحبًا بك في Strategix ، وهو تطبيق ويب للشطرنج يعمل بنسبة 100٪ دون اتصال بالإنترنت. من خلال الوصول إلى Strategix أو استخدامه ، فإنك توافق على الالتزام بهذه الشروط والأحكام وسياسة الخصوصية الخاصة بنا. إذا كنت لا توافق على أي من هذه الشروط ، فلا تستخدم التطبيق.

2. الملكية والاعتمادات
Strategix مملوكة لشركة Benzanox Studios. على الرغم من استخدام Gemini 2.5 Pro AI في التطوير ، فإن جميع حقوق الملكية الفكرية للتطبيق تعود إليك بصفتك مالك التطبيق.

3. استخدام التطبيق
3.1 Strategix هو تطبيق مخصص لأغراض الترفيه وتعلم الشطرنج.
3.2 أنت توافق على عدم استخدام التطبيق في أنشطة غير قانونية ، بما في ذلك القرصنة أو الاختراق أو انتهاك حقوق الغير.
3.3 يعمل التطبيق بشكل كامل دون اتصال بالإنترنت ولا يجمع أي بيانات خارجية.

4. محتوى المستخدم والتخزين
4.1 يتم الاحتفاظ بجميع البيانات التي تنشئها ، بما في ذلك الألعاب والإعدادات ، حصريًا في LocalStorage بجهازك.
4.2 لا يقوم Strategix بجمع أو نقل أو مشاركة البيانات الشخصية أو بيانات اللعبة مع خوادم خارجية.
4.3 أنت مسؤول عن الحفاظ على أمان جهازك والبيانات المخزنة محليًا.

5. ترخيص الاستخدام
5.1 يتم منحك ترخيصًا محدودًا وغير حصري وغير قابل للتحويل لاستخدام Strategix في متصفحك.
5.2 لا يُسمح لك بإعادة توزيع التطبيق أو بيعه أو تفكيكه أو إنشاء أعمال مشتقة منه دون إذن صريح.

6. الملكية الفكرية
6.1 جميع حقوق النشر والعلامات التجارية والتصميمات الرسومية لـ Strategix ، بما في ذلك قطع الشطرنج والواجهة ، هي ملك لشركة Benzanox Studios.
6.2 لا يكتسب المستخدم أي حقوق ملكية فكرية باستخدام التطبيق.

7. تحديد المسؤولية
7.1 يتم توفير Strategix "كما هو" ولا يضمن خلو التطبيق من الأخطاء أو الانقطاعات.
7.2 لن تكون Benzanox Studios مسؤولة عن أي أضرار مباشرة أو غير مباشرة أو عرضية أو تبعية تنشأ عن استخدام التطبيق.

8. التعديلات والتحديثات
8.1 قد تقوم Benzanox Studios بتحديث أو تعديل Strategix وهذه الشروط في أي وقت.
8.2 يوصى بمراجعة هذا القسم بشكل دوري. يعني الاستخدام المستمر قبول التغييرات.

9. مسؤولية المستخدم
9.1 المستخدم مسؤول عن الاستخدام السليم للتطبيق وعن الصيانة الآمنة لبياناته المحلية.
9.2 يوصى بعمل نسخ احتياطية من الألعاب والإعدادات المهمة لتجنب فقدان المعلومات بسبب فشل الجهاز.
9.3 أي سوء استخدام يسبب ضررًا لأطراف ثالثة هو مسؤولية المستخدم الحصرية.

10. سياسة الخصوصية
10.1 لا يتم جمع أي بيانات شخصية من المستخدمين.
10.2 يتم تخزين جميع المعلومات حول الألعاب والإحصائيات والإعدادات فقط في LocalStorage بمتصفحك.
10.3 لا تتم مشاركة أي معلومات مع أطراف ثالثة تحت أي ظرف من الظروف.
10.4 لا يقوم التطبيق بتتبع أو استخدام ملفات تعريف ارتباط خارجية ؛ أي ملفات تعريف ارتباط مستخدمة هي للتشغيل الداخلي فقط.

11. القانون المعمول به والاختصاص القضائي
11.1 تخضع هذه الشروط لقانون جمهورية باراغواي.
11.2 سيتم حل أي نزاع قانوني يتعلق بالتطبيق حصريًا في محاكم أسونسيون ، باراغواي.

12. الاتصال
لأسئلة حول هذه الشروط ، يمكنك الاتصال بنا على: [dinerocor@hotmail.com]

باستخدام Strategix ، فإنك تقبل هذه الشروط والأحكام وسياسة الخصوصية الخاصة بنا بالكامل ، مع التأكيد على عدم جمع أي بيانات شخصية أو نقلها خارج جهازك.`,
      agree: 'لقد قرأت ووافقت على الشروط والأحكام.',
      accept: 'قبول',
    },
    common: {
        back: 'رجوع',
        cancel: 'إلغاء',
        comingSoon: 'قريباً',
    }
  },
  hi: {
    mainMenu: {
      title: 'Strategix',
      play: 'शतरंज खेलें',
      load: 'गेम लोड करें',
      stats: 'आंकड़े',
      settings: 'सेटिंग्स',
      help: 'सहायता / ट्यूटोरियल',
      exit: 'बाहर निकलें',
    },
    playMenu: {
        title: 'शतरंज खेलें',
        vsAI: 'बनाम AI',
        local: 'बनाम मानव',
        tutorial: 'प्रशिक्षण / ट्यूटोरियल',
        difficulty: 'कठिनाई',
        easy: 'आसान',
        medium: 'मध्यम',
        hard: 'कठिन',
        master: 'मास्टर',
        easyDesc: 'सीखने के लिए एक आकस्मिक खेल।',
        mediumDesc: 'अधिकांश खिलाड़ियों के लिए एक संतुलित चुनौती।',
        hardDesc: 'एक सख्त प्रतिद्वंद्वी जो गलतियों की सजा देता है।',
        masterDesc: 'अधिकतम चुनौती। लगभग-इष्टतम चालें चलता है।',
        pieceColor: 'मोहरों का रंग',
        white: 'सफ़ेद',
        black: 'काला',
        random: 'यादृच्छिक',
        moveHints: 'चाल संकेत',
        start: 'खेल शुरू करें',
        onlineComingSoon: 'ऑनलाइन मोड - जल्द आ रहा है',
    },
    loadMenu: {
        title: 'गेम लोड करें',
        empty: 'कोई सहेजा हुआ गेम नहीं मिला।',
        load: 'लोड',
        delete: 'हटाएं',
    },
    statsMenu: {
        title: 'आंकड़े',
        totalGames: 'कुल खेल',
        wins: 'जीत',
        losses: 'हार',
        draws: 'ड्रॉ',
        rating: 'ऑफलाइन रेटिंग',
        winLossRatio: 'जीत/हार अनुपात',
        mostUsedOpenings: 'सबसे ज्यादा इस्तेमाल की जाने वाली ओपनिंग',
    },
    settingsMenu: {
        title: 'सेटिंग्स',
        language: 'भाषा',
        sound: 'ध्वनि',
        music: 'संगीत',
        on: 'चालू',
        off: 'बंद',
        theme: 'बोर्ड थीम',
        light: 'हल्का',
        dark: 'गहरा',
        animationSpeed: 'एनिमेशन गति',
        fast: 'तेज़',
        normal: 'सामान्य',
        slow: 'धीमा',
        resetStats: 'आंकड़े रीसेट करें',
        resetConfirm: 'क्या आप वाकई सभी आंकड़े रीसेट करना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता।',
        confirm: 'पुष्टि करें',
    },
    helpMenu: {
        title: 'सहायता / ट्यूटोरियल',
        rules: 'मूल नियम (FIDE)',
        pawn: 'प्यादा: एक वर्ग आगे बढ़ता है, लेकिन अपनी पहली चाल पर दो। तिरछे कब्जा करता है।',
        knight: 'घोड़ा: "L" आकार में चलता है (एक दिशा में दो वर्ग, फिर एक लंबवत)।',
        bishop: 'ऊंट: तिरछे किसी भी संख्या में वर्ग चलता है।',
        rook: 'हाथी: क्षैतिज या लंबवत रूप से किसी भी संख्या में वर्ग चलता है।',
        queen: 'रानी: हाथी और ऊंट की शक्ति को जोड़ती है।',
        king: 'राजा: किसी भी दिशा में एक वर्ग चलता है।',
        faq: 'FAQ',
        faq1_q: 'क्या यह ऐप 100% ऑफलाइन है?',
        faq1_a: 'हां, सभी सुविधाएं इंटरनेट कनेक्शन के बिना काम करने के लिए डिज़ाइन की गई हैं।',
        viewTerms: 'नियम और शर्तें देखें',
    },
    termsModal: {
      title: 'नियम और शर्तें',
      content: `STRATEGIX नियम और शर्तें और गोपनीयता नीति

अंतिम अपडेट: 21 सितंबर, 2025

1. परिचय
Strategix में आपका स्वागत है, जो एक 100% ऑफ़लाइन शतरंज वेब एप्लिकेशन है। Strategix तक पहुँचने या उसका उपयोग करने पर, आप इन नियमों और शर्तों और हमारी गोपनीयता नीति से बाध्य होने के लिए सहमत हैं। यदि आप इनमें से किसी भी शर्त से सहमत नहीं हैं, तो एप्लिकेशन का उपयोग न करें।

2. स्वामित्व और क्रेडिट
Strategix का स्वामित्व बेनज़ानॉक्स स्टूडियो के पास है। हालाँकि विकास के लिए जेमिनी 2.5 प्रो एआई का उपयोग किया गया था, ऐप के सभी बौद्धिक संपदा अधिकार ऐप के मालिक के रूप में आपके हैं।

3. एप्लिकेशन का उपयोग
3.1 Strategix मनोरंजन और शतरंज सीखने के उद्देश्यों के लिए एक एप्लिकेशन है।
3.2 आप एप्लिकेशन का उपयोग अवैध गतिविधियों के लिए नहीं करने के लिए सहमत हैं, जिसमें पायरेसी, हैकिंग या तीसरे पक्ष के अधिकारों का उल्लंघन शामिल है।
3.3 एप्लिकेशन पूरी तरह से ऑफ़लाइन चलता है और कोई बाहरी डेटा एकत्र नहीं करता है।

4. उपयोगकर्ता सामग्री और भंडारण
4.1 आपके द्वारा उत्पन्न सभी डेटा, जिसमें गेम और सेटिंग्स शामिल हैं, विशेष रूप से आपके डिवाइस के लोकलस्टोरेज में रखे जाते हैं।
4.2 Strategix बाहरी सर्वर के साथ व्यक्तिगत или गेम डेटा एकत्र, प्रसारित या साझा नहीं करता है।
4.3 आप अपने डिवाइस और स्थानीय रूप से संग्रहीत डेटा की सुरक्षा बनाए रखने के लिए जिम्मेदार हैं।

5. उपयोग का लाइसेंस
5.1 आपको अपने ब्राउज़र में Strategix का उपयोग करने के लिए एक सीमित, गैर-अनн्य, गैर-हस्तांतरणीय लाइसेंस प्रदान किया जाता है।
5.2 आपको स्पष्ट प्राधिकरण के बिना एप्लिकेशन से व्युत्पन्न कार्यों को पुनर्वितरित करने, बेचने, डीकंपाइल करने या बनाने की अनुमति नहीं है।

6. बौद्धिक संपदा
6.1 शतरंज के मोहरों और इंटरफ़ेस सहित, Strategix के सभी कॉपीराइट, ट्रेडमार्क और ग्राफिक डिज़ाइन, बेनज़ानॉक्स स्टूडियो की संपत्ति हैं।
6.2 उपयोगकर्ता एप्लिकेशन का उपयोग करके कोई बौद्धिक संपदा अधिकार प्राप्त नहीं करता है।

7. देयता की सीमा
7.1 Strategix "जैसा है" प्रदान किया जाता है और यह गारंटी नहीं देता है कि एप्लिकेशन त्रुटियों या रुकावटों से मुक्त होगा।
7.2 बेनज़ानॉक्स स्टूडियो एप्लिकेशन के उपयोग से होने वाले किसी भी प्रत्यक्ष, अप्रत्यक्ष, आकस्मिक या परिणामी नुकसान के लिए उत्तरदायी नहीं होगा।

8. संशोधन और अपडेट
8.1 बेनज़ानॉक्स स्टूडियो किसी भी समय Strategix और इन शर्तों को अपडेट या संशोधित कर सकता है।
8.2 इस अनुभाग की समय-समय पर समीक्षा करने की अनुशंसा की जाती है। निरंतर उपयोग परिवर्तनों की स्वीकृति का तात्पर्य है।

9. उपयोगकर्ता की जिम्मेदारी
9.1 उपयोगकर्ता एप्लिकेशन के उचित उपयोग और अपने स्थानीय डेटा के सुरक्षित रखरखाव के लिए जिम्मेदार है।
9.2 डिवाइस की विफलताओं के कारण सूचना के नुकसान से बचने के लिए महत्वपूर्ण गेम और सेटिंग्स का बैकअप बनाने की अनुशंसा की जाती है।
9.3 तीसरे पक्ष को नुकसान पहुँचाने वाला कोई भी दुरुपयोग उपयोगकर्ता की अनन्य जिम्मेदारी है।

10. गोपनीयता नीति
10.1 उपयोगकर्ताओं से कोई व्यक्तिगत डेटा एकत्र नहीं किया जाता है।
10.2 गेम, आँकड़े और सेटिंग्स के बारे में सभी जानकारी केवल आपके ब्राउज़र के लोकलस्टोरेज में संग्रहीत होती है।
10.3 किसी भी परिस्थिति में तीसरे पक्ष के साथ कोई जानकारी साझा नहीं की जाती है।
10.4 एप्लिकेशन ट्रैकिंग या बाहरी कुकीज़ का उपयोग नहीं करता है; उपयोग की जाने वाली कोई भी कुकीज़ सख्ती से आंतरिक संचालन के लिए होती है।

11. लागू कानून और क्षेत्राधिकार
11.1 ये शर्तें पराग्वे गणराज्य के कानून द्वारा शासित होती हैं।
11.2 एप्लिकेशन से संबंधित कोई भी कानूनी विवाद विशेष रूप से असुनसियन, पराग्वे की अदालतों में हल किया जाएगा।

12. संपर्क
इन शर्तों के बारे में प्रश्नों के लिए, आप हमसे संपर्क कर सकते हैं: [dinerocor@hotmail.com]

Strategix का उपयोग करके, आप इन नियमों और शर्तों और हमारी गोपनीयता नीति को पूरी तरह से स्वीकार करते हैं, इस आश्वासन के साथ कि आपके डिवाइस के बाहर कोई व्यक्तिगत डेटा एकत्र या प्रसारित नहीं किया जाता है।`,
      agree: 'मैंने नियम और शर्तें पढ़ ली हैं और उनसे सहमत हूं।',
      accept: 'स्वीकार करें',
    },
    common: {
        back: 'वापस',
        cancel: 'रद्द करें',
        comingSoon: 'जल्द आ रहा है',
    }
  },
  tr: {
    mainMenu: {
      title: 'Strategix',
      play: 'Satranç Oyna',
      load: 'Oyunu Yükle',
      stats: 'İstatistikler',
      settings: 'Ayarlar',
      help: 'Yardım / Öğretici',
      exit: 'Çıkış',
    },
    playMenu: {
        title: 'Satranç Oyna',
        vsAI: 'vs. Yapay Zeka',
        local: 'vs. İnsan',
        tutorial: 'Eğitim / Öğretici',
        difficulty: 'Zorluk',
        easy: 'Kolay',
        medium: 'Orta',
        hard: 'Zor',
        master: 'Usta',
        easyDesc: 'Öğrenmek için iyi, rahat bir oyun.',
        mediumDesc: 'Çoğu oyuncu için dengeli bir meydan okuma.',
        hardDesc: 'Hataları cezalandıran zorlu bir rakip.',
        masterDesc: 'Maksimum meydan okuma. Neredeyse en uygun hamleleri oynar.',
        pieceColor: 'Taş Rengi',
        white: 'Beyaz',
        black: 'Siyah',
        random: 'Rastgele',
        moveHints: 'Hamle İpuçları',
        start: 'Oyunu Başlat',
        onlineComingSoon: 'Çevrimiçi Mod - Yakında',
    },
    loadMenu: {
        title: 'Oyunu Yükle',
        empty: 'Kayıtlı oyun bulunamadı.',
        load: 'Yükle',
        delete: 'Sil',
    },
    statsMenu: {
        title: 'İstatistikler',
        totalGames: 'Toplam Oyun',
        wins: 'Galibiyet',
        losses: 'Mağlubiyet',
        draws: 'Beraberlik',
        rating: 'Çevrimdışı Puan',
        winLossRatio: 'Galibiyet/Mağlubiyet Oranı',
        mostUsedOpenings: 'En Çok Kullanılan Açılışlar',
    },
    settingsMenu: {
        title: 'Ayarlar',
        language: 'Dil',
        sound: 'Ses',
        music: 'Müzik',
        on: 'Açık',
        off: 'Kapalı',
        theme: 'Tahta Teması',
        light: 'Açık',
        dark: 'Koyu',
        animationSpeed: 'Animasyon Hızı',
        fast: 'Hızlı',
        normal: 'Normal',
        slow: 'Yavaş',
        resetStats: 'İstatistikleri Sıfırla',
        resetConfirm: 'Tüm istatistikleri sıfırlamak istediğinizden emin misiniz? Bu işlem geri alınamaz.',
        confirm: 'Onayla',
    },
    helpMenu: {
        title: 'Yardım / Öğretici',
        rules: 'Temel Kurallar (FIDE)',
        pawn: 'Piyon: Bir kare ileri gider, ancak ilk hamlesinde iki kare. Çapraz olarak taş alır.',
        knight: 'At: "L" şeklinde hareket eder (bir yönde iki kare, sonra dikey olarak bir kare).',
        bishop: 'Fil: Çapraz olarak istenilen sayıda kare hareket eder.',
        rook: 'Kale: Yatay veya dikey olarak istenilen sayıda kare hareket eder.',
        queen: 'Vezir: Kale ve filin gücünü birleştirir.',
        king: 'Şah: Herhangi bir yönde bir kare hareket eder.',
        faq: 'SSS',
        faq1_q: 'Bu uygulama %100 çevrimdışı mı?',
        faq1_a: 'Evet, tüm özellikler internet bağlantısı olmadan çalışacak şekilde tasarlanmıştır.',
        viewTerms: 'Şartlar ve Koşulları Görüntüle',
    },
    termsModal: {
      title: 'Şartlar ve Koşullar',
      content: `STRATEGIX ŞARTLAR VE KOŞULLAR VE GİZLİLİK POLİTİKASI

Son güncelleme: 21 Eylül 2025

1. Giriş
%100 çevrimdışı bir satranç web uygulaması olan Strategix'e hoş geldiniz. Strategix'e erişerek veya kullanarak, bu Şartlar ve Koşullar ile Gizlilik Politikamıza bağlı kalmayı kabul edersiniz. Bu şartlardan herhangi birini kabul etmiyorsanız, uygulamayı kullanmayın.

2. Sahiplik ve Krediler
Strategix, Benzanox Studios'a aittir. Geliştirme için Gemini 2.5 Pro AI kullanılmış olsa da, uygulamanın tüm fikri mülkiyet hakları uygulama sahibi olarak size aittir.

3. Uygulamanın Kullanımı
3.1 Strategix, eğlence ve satranç öğrenme amaçlı bir uygulamadır.
3.2 Uygulamayı korsanlık, hackleme veya üçüncü taraf haklarını ihlal etme gibi yasa dışı faaliyetler için kullanmamayı kabul edersiniz.
3.3 Uygulama tamamen çevrimdışı çalışır ve herhangi bir harici veri toplamaz.

4. Kullanıcı İçeriği ve Depolama
4.1 Oyunlar ve ayarlar da dahil olmak üzere sizin tarafınızdan oluşturulan tüm veriler, yalnızca cihazınızın LocalStorage'ında tutulur.
4.2 Strategix, kişisel veya oyun verilerini harici sunucularla toplamaz, iletmez veya paylaşmaz.
4.3 Cihazınızın ve yerel olarak depolanan verilerin güvenliğini sağlamaktan siz sorumlusunuz.

5. Kullanım Lisansı
5.1 Tarayıcınızda Strategix'i kullanmanız için size sınırlı, münhasır olmayan, devredilemez bir lisans verilir.
5.2 Açık izin olmadan uygulamadan yeniden dağıtım yapmak, satmak, kaynak koda dönüştürmek veya türev çalışmalar oluşturmak yasaktır.

6. Fikri Mülkiyet
6.1 Satranç taşları ve arayüzü de dahil olmak üzere Strategix'in tüm telif hakları, ticari markaları ve grafik tasarımları Benzanox Studios'un mülkiyetindedir.
6.2 Kullanıcı, uygulamayı kullanarak herhangi bir fikri mülkiyet hakkı elde etmez.

7. Sorumluluğun Sınırlandırılması
7.1 Strategix "olduğu gibi" sağlanır ve uygulamanın hatasız veya kesintisiz olacağını garanti etmez.
7.2 Benzanox Studios, uygulamanın kullanımından kaynaklanan doğrudan, dolaylı, arızi veya sonuç olarak ortaya çıkan zararlardan sorumlu olmayacaktır.

8. Değişiklikler ve Güncellemeler
8.1 Benzanox Studios, Strategix'i ve bu şartları herhangi bir zamanda güncelleyebilir veya değiştirebilir.
8.2 Bu bölümün periyodik olarak gözden geçirilmesi önerilir. Kullanıma devam etmek, değişikliklerin kabul edildiği anlamına gelir.

9. Kullanıcı Sorumluluğu
9.1 Kullanıcı, uygulamanın doğru kullanımından ve yerel verilerinin güvenli bir şekilde bakımından sorumludur.
9.2 Cihaz arızaları nedeniyle bilgi kaybını önlemek için önemli oyunların ve ayarların yedeklerinin alınması önerilir.
9.3 Üçüncü şahıslara zarar veren herhangi bir kötüye kullanım, yalnızca kullanıcının sorumluluğundadır.

10. Gizlilik Politikası
10.1 Kullanıcılardan hiçbir kişisel veri toplanmaz.
10.2 Oyunlar, istatistikler ve ayarlar hakkındaki tüm bilgiler yalnızca tarayıcınızın LocalStorage'ında saklanır.
10.3 Hiçbir koşulda üçüncü taraflarla bilgi paylaşılmaz.
10.4 Uygulama izleme yapmaz veya harici çerezler kullanmaz; kullanılan tüm çerezler kesinlikle dahili işletim içindir.

11. Uygulanacak Hukuk ve Yargı Yetkisi
11.1 Bu şartlar Paraguay Cumhuriyeti yasalarına tabidir.
11.2 Uygulama ile ilgili herhangi bir yasal anlaşmazlık yalnızca Asunción, Paraguay mahkemelerinde çözülecektir.

12. İletişim
Bu şartlarla ilgili sorularınız için bizimle şu adresten iletişime geçebilirsiniz: [dinerocor@hotmail.com]

Strategix'i kullanarak, bu Şartlar ve Koşulları ve Gizlilik Politikamızı bütünüyle kabul etmiş olursunuz ve hiçbir kişisel verinin cihazınızın dışına toplanmadığından veya iletilmediğinden emin olabilirsiniz.`,
      agree: 'Şartları ve koşulları okudum ve kabul ediyorum.',
      accept: 'Kabul Et',
    },
    common: {
        back: 'Geri',
        cancel: 'İptal',
        comingSoon: 'Yakında',
    }
  }
};